### ISSUE TITLE
[BUG] playwright-cli does not work with NPX on Node.js 14 and 12

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright-cli#136]
extracted from #117

Reproducible with:

- Virtual machine ubuntu and Node.js 14 - NPX 6.14.8
- Official Playwright Docker image (since its Node.js 12 based) - NPX 6.14.8

Works with Node.js 15

Stack trace:

```
root@f3029c2c593c:/# npx playwright-cli
internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module '/root/.npm/_npx/12/lib/node_modules/playwright-cli/node_modules/playwright/install.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! playwright@1.6.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the playwright@1.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-14T19_47_53_232Z-debug.log
Install for [ 'playwright-cli@latest' ] failed with code 1
```

```
docker run -it mcr.microsoft.com/playwright:next-focal /bin/bash
# or
docker run -it mcr.microsoft.com/playwright:next-bionic /bin/bash

# and then after both
npx playwright-cli
# now the error comes up
```

**Comment by pavelfeldman** [comment]
Looks similar to https://supportcenter.devexpress.com/ticket/details/t914123/the-error-cannot-find-module-root-npm-npx-3704-lib-node-modules-devextreme-cli-node

As per suggestions there, either npm install or don't use root!
