### ISSUE TITLE
[npm package] Provide type stubs

### ISSUE THREAD

**Issue by xylix** [microsoft/playwright-cli#154]
Currently it is quite difficult to make use of playwright-cli as an imported npm package in typescript projects. Would it be possible to provide the type stubs along with the compiled .js on `npm install playwright-cli`?

**Comment by xylix** [comment]
Adding stubs 

Testing some things locally, it seems the logic is quite bound to the cli execution model

With these changes

```
 ~/C/r/n/p/playwright-cli (master)> git diff
diff --git a/src/cli.ts b/src/cli.ts
index 52351ee..e2ac280 100755
--- a/src/cli.ts
+++ b/src/cli.ts
@@ -338,7 +338,7 @@ async function pdf(options: Options, captureOptions: CaptureOptions, url: string
   await browser.close();
 }

-async function codegen(options: Options, url: string | undefined, target: string, outputFile?: string) {
+export async function codegen(options: Options, url: string | undefined, target: string, outputFile?: string) {
   let languageGenerator: LanguageGenerator;

   switch (target) {
diff --git a/tsconfig.json b/tsconfig.json
index 52b6946..e87dc05 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -7,8 +7,9 @@
     "rootDir": "./src",
     "outDir": "./lib",
     "strict": true,
-    "declaration": false,
-    "noUnusedLocals": true
+    "declaration": true,
+    "noUnusedLocals": true,
+    "downlevelIteration": true
   },
   "compileOnSave": true,
   "include": ["src/**/*.ts"],
```

Trying to call codegen function fails with 

```
codegen({browser: "chromium", geolocation: "", lang: "", proxyServer: "", timezone: "", colorScheme: undefined, device: undefined, timeout: undefined, viewportSize: undefined, userAgent: undefined},"https://google.com", "python")
```

```
Uncaught ReferenceError: cli_1 is not defined
    at /Users/kerkko/Code/robotframework-browser/node/playwright-wrapper/[eval].ts:1:1
    at Script.runInThisContext (vm.js:132:18)
    at exec (/Users/kerkko/.config/nvm/14.15.1/lib/node_modules/ts-node/src/repl.ts:196:17)
    at /Users/kerkko/.config/nvm/14.15.1/lib/node_modules/ts-node/src/repl.ts:186:27
    at Array.reduce (<anonymous>)
    at _eval (/Users/kerkko/.config/nvm/14.15.1/lib/node_modules/ts-node/src/repl.ts:185:18)
    at evalCode (/Users/kerkko/.config/nvm/14.15.1/lib/node_modules/ts-node/src/repl.ts:77:12)
    at REPLServer.nodeEval (/Users/kerkko/.config/nvm/14.15.1/lib/node_modules/ts-node/src/repl.ts:91:16)
    at bound (domain.js:430:14)
    at REPLServer.runBound [as eval] (domain.js:443:12)
```
